[book]
title = "Rustc Librarification Project (formerly Stable MIR)"
language = "en"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/rust-lang/project-stable-mir"
site-url = "/project-stable-mir/"

[output.html.playground]
runnable = false

[rust]
edition = "2021"

[build]
build-dir = "build"